name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtest-dev

      - name: Run tests
        run: make GTEST_DIR=/usr run-test
